version: '3.5'
services:
  mysql_superkompras:
    container_name: mysql_${GRUPO_PROJETO}
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${SENHA_ADMIN_INTRANET}
      MYSQL_DATABASE: mydb
      MYSQL_USER: db`root
      MYSQL_PASSWORD: ${SENHA_ADMIN_INTRANET}
      MYSQL_ROOT_HOST: "%"
    ports:
    - "3306"
    volumes:
      - ${PASTA_ARQUIVOS}/bancorelacional:/var/lib/mysql:Z
    restart: always
    networks:
      bancoSK:
         ipv4_address: ${IP_BANCO_DADOS_RELACIONAL}
  phpmyadmin:
    image:  phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin${GRUPO_PROJETO}
    environment:
     - PMA_HOSTS=${NOME_HOST_BANCO_RELACIONAL}
     - PMA_USER=root
     - PMA_PASSWORD=${SENHA_ADMIN_INTRANET}
    restart: always
    ports:
     - "80"
    networks:
      bancoSK:
      traefik_proxy:
    depends_on:
    -  mysql_superkompras
    extra_hosts:
     - "${NOME_HOST_BANCO_RELACIONAL}:${IP_BANCO_DADOS_RELACIONAL}"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=superkomprasAcessoBanco"
      - "traefik.frontend.rule=Host:bancorelacional.${ENDERECO_INTRANET}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=superkompras.com.br"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  intranet:
    container_name: Intranet_${GRUPO_PROJETO}
    image: ${CLIENTE}/${GRUPO_PROJETO}
    networks:
    - traefik_proxy
    - bancoSK
    depends_on:
    -  mysql_superkompras
    extra_hosts:
     - "${NOME_HOST_BANCO_RELACIONAL}:${IP_BANCO_DADOS_RELACIONAL}"
    volumes:
      - ${PASTA_ARQUIVOS}:/home/servidorSBFW/arquivosDeEntidade:Z
    labels:
      - "traefik.enable=true"
      - "traefik.backend=superkomprasIntranet"
      - "traefik.frontend.rule=Host:${ENDERECO_INTRANET}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=superkompras.com.br"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customFrameOptionsValue=allow-from ${ENDERECO_INTRANET}"



networks:
 traefik_proxy:
   external:
      name: traefik_proxy
 bancoSK:
   driver: bridge
   ipam:
      driver: default
      config:
      - subnet: ${SUBREDE_INTRANET}